using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Serialization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SWD_GUI_Assignment.Models;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    //Based on the default autogenerated ASP NET application with Identity framework
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;

        public ApplicationDbContext Context
        {
            get
            {
                return _context ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set
            {
                _context = value;
            }
        }

        public ActionResult Index()
        {
            //Context.Database.Delete();
            return View();
        }

        public ActionResult Sensors()
        {
            //Context.Database.Delete();
            return View();
        }

        // GET: /Manage/Index
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            //Create a serializer
            XmlSerializer serializer = new XmlSerializer(typeof(List<Lokation>));

            // Deserialize all the lokations.
            var temp = (List<Lokation>)serializer.Deserialize(file.InputStream);
            //Add each by their ID. 
            foreach (var newLokation in temp)
            {
                //Simplify the array structure to a readable string
                var MeasurementTreeSimplified = "";
                foreach (var newLokationMeasurementTree in newLokation.MeasurementTrees)
                {
                    MeasurementTreeSimplified +=
                        newLokationMeasurementTree.Sort + ": " + newLokationMeasurementTree.Antal + ", ";
                }

                //Make new entry for DB
                LokationWithSimpleTree simpleLokation = new LokationWithSimpleTree()
                {
                    By = newLokation.By,
                    Id = newLokation.Id,
                    MeasurementTrees = MeasurementTreeSimplified,
                    Navn = newLokation.Navn,
                    Postnummer = newLokation.Postnummer,
                    Vej = newLokation.Vej,
                    Vejnummer = newLokation.Vejnummer
                };

                //Add it. 
                Context.Lokations.AddOrUpdate(simpleLokation);
            }

            //Save changes
            Context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }


        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(RegistrerSensorViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Find the given user to attach his name to the sensor. 
                var userId = User.Identity.GetUserId();
                var user = Context.Users.Where(x => x.Id == userId).FirstOrDefault();

                //Create sensor
                var sensor = new Sensor()
                {
                    CreatedBy = user.Navn,
                    Lat = model.Lat,
                    Lon = model.Lon,
                    LokationsId = model.LokationsId,
                    Træart = model.Træart,
                    Sensorid = model.SensorId.ToUpper()
                };

                //Add to database
                Context.Sensors.Add(sensor);
                Context.SaveChanges();
                //Return with blank form
                return RedirectToAction("Index", "Home");
            }

            // Something failed - Return with model. 
            return View(model);
        }

    }
}