using System.Web;
using System.Web.Mvc;
//Based on the default autogenerated ASP NET application with Identity framework
namespace WebApplication1
{
    public class FilterConfig
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
        }
    }
}
